# Generated by Django 4.2.10 on 2024-03-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0002_remove_survey_description_response_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='response',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='student',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
