# Generated by Django 4.2.10 on 2024-03-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Survey', '0003_remove_question_survey_remove_response_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_mail', models.CharField(max_length=255)),
                ('food_quality', models.PositiveIntegerField()),
                ('food_quantity', models.PositiveIntegerField()),
                ('food_pricing', models.PositiveIntegerField()),
                ('satisfaction', models.PositiveIntegerField()),
                ('hygiene_satisfaction', models.BooleanField()),
                ('frequency_of_use', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('rarely', 'Rarely')], max_length=20)),
            ],
        ),
    ]
