# Generated by Django 4.2.10 on 2024-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0005_choice_question_response_survey_delete_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
