# Generated by Django 4.2.10 on 2024-03-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0006_choice_answer_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenStaticSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_id', models.CharField(max_length=255, unique=True)),
                ('food_quality', models.CharField(choices=[('best', 'Best'), ('satisfactory', 'Satisfactory'), ('moderate', 'Moderate'), ('worst', 'Worst')], max_length=20)),
                ('food_quantity', models.CharField(blank=True, choices=[('best', 'Best'), ('satisfactory', 'Satisfactory'), ('moderate', 'Moderate'), ('worst', 'Worst')], max_length=20, null=True)),
                ('food_pricing', models.CharField(blank=True, choices=[('best', 'Best'), ('satisfactory', 'Satisfactory'), ('moderate', 'Moderate'), ('worst', 'Worst')], max_length=20, null=True)),
                ('canteen_satisfaction', models.CharField(blank=True, choices=[('best', 'Best'), ('satisfactory', 'Satisfactory'), ('moderate', 'Moderate'), ('worst', 'Worst')], max_length=20, null=True)),
                ('canteen_environment', models.CharField(blank=True, choices=[('best', 'Best'), ('satisfactory', 'Satisfactory'), ('moderate', 'Moderate'), ('worst', 'Worst')], max_length=20, null=True)),
                ('canteen_usage', models.CharField(blank=True, choices=[('daily', 'Daily'), ('occasionally', 'Occasionally'), ('never', 'Never')], max_length=20, null=True)),
                ('canteen_serial', models.CharField(blank=True, choices=[('best', 'Best'), ('satisfactory', 'Satisfactory'), ('moderate', 'Moderate'), ('worst', 'Worst')], max_length=20, null=True)),
                ('initial_menu', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('preferred_menu', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_behavior', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
