# Generated by Django 4.2.10 on 2024-03-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0007_canteenstaticsurvey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanteenStaticSurvey',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='response',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
